/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/terrain/fixed_terrain_comp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.atoms.geometry} material={materials.DefaultMaterial} position={[1.536, -1.972, -0.839]} scale={3.328} />
        <mesh geometry={nodes.Grid.geometry} material={materials['Material.003']} position={[0, 24.536, 0]} scale={63.217} />
        <mesh geometry={nodes.atoms001.geometry} material={materials.Material_0} position={[1.536, -1.972, -0.839]} scale={3.328} />
      </RigidBody>

      {/* INVISIBLE BOUNDARY WALLS to prevent falling off the world */}
      <RigidBody type="fixed">
        <CuboidCollider position={[60, 20, 0]} args={[1, 50, 60]} />  {/* Right boundary */}
        <CuboidCollider position={[-60, 20, 0]} args={[1, 50, 60]} /> {/* Left boundary */}
        <CuboidCollider position={[0, 20, 60]} args={[60, 50, 1]} />  {/* Back boundary */}
        <CuboidCollider position={[0, 20, -60]} args={[60, 50, 1]} /> {/* Front boundary */}
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/models/terrain/fixed_terrain_comp.glb')
