/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Made_terrain.glb -T 
Files: Made_terrain.glb [49.75MB] > C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\terrain\Made_terrain-transformed.glb [1.92MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/terrain/Made_terrain.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.atoms.geometry} material={materials.DefaultMaterial} position={[1.536, -1.972, -0.839]} scale={3.328} />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.Grid.geometry} material={materials['Material.003']} position={[0, 24.536, 0]} scale={63.217} />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.atoms001.geometry} material={materials.Material_0} position={[1.536, -1.972, -0.839]} scale={3.328} />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.Object_2.geometry} material={materials.k909090} position={[-12.691, 0.448, 10.671]} rotation={[-3.031, -0.949, 0.836]} scale={5.666} />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.Object_3.geometry} material={materials.kffffff} position={[-12.691, 0.448, 10.671]} rotation={[-3.031, -0.949, 0.836]} scale={5.666} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/models/terrain/Made_terrain.glb')
