/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 neuronal_cell_environment-v1.glb --transform 
Files: neuronal_cell_environment-v1.glb [10.4MB] > C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\terrain\neuronal_cell_environment-v1-transformed.glb [6.98MB] (33%)
Author: ryannsoup (https://sketchfab.com/ryannsoup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neuronal-cell-environment-11fc6dbcc1594e9a806601bb7480f315
Title: Neuronal Cell Environment
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/terrain/neuronal_cell_environment_v1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Neuron_and_Oligos16" position={[-0.266, 0.06, -0.22]} rotation={[-1.659, 0.452, 2.027]} scale={0.01}>
          <group name="Main_Neuron1" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Main_Neuron1_phong1_0" geometry={nodes.Main_Neuron1_phong1_0.geometry} material={materials.phong1} />
          </group>
          <group name="Main_Neuron2" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Main_Neuron2_phong1_0" geometry={nodes.Main_Neuron2_phong1_0.geometry} material={materials.phong1} />
          </group>
        </group>
        <group name="Electrical_pulses2" position={[-0.266, 0.06, -0.22]} rotation={[-1.659, 0.452, 2.027]} scale={0.01}>
          <group name="pCube5" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="pCube5_phong2_0_1" geometry={nodes.pCube5_phong2_0_1.geometry} material={materials.phong2} />
          </group>
          <group name="pCube6" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="pCube6_phong2_0" geometry={nodes.pCube6_phong2_0.geometry} material={materials.phong2} />
          </group>
          <group name="pCube1" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="pCube1_phong2_0" geometry={nodes.pCube1_phong2_0.geometry} material={materials.phong2} />
          </group>
          <group name="pCube4" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="pCube4_phong2_0" geometry={nodes.pCube4_phong2_0.geometry} material={materials.phong2} />
          </group>
          <group name="pCube3" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="pCube3_phong2_0" geometry={nodes.pCube3_phong2_0.geometry} material={materials.phong2} />
          </group>
        </group>
        <group name="Oligo3" position={[-0.266, 0.06, -0.22]} rotation={[-1.659, 0.452, 2.027]} scale={0.01}>
          <group name="Oligodendrocyte" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Oligodendrocyte_Myelin3_0_1" geometry={nodes.Oligodendrocyte_Myelin3_0_1.geometry} material={materials.Myelin3} />
          </group>
          <group name="Inside_Oligo1" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Inside_Oligo1_m_oligo_inside_0_1" geometry={nodes.Inside_Oligo1_m_oligo_inside_0_1.geometry} material={materials.m_oligo_inside} />
          </group>
        </group>
        <group name="Oligo4" position={[-0.266, 0.06, -0.22]} rotation={[-1.659, 0.452, 2.027]} scale={0.01}>
          <group name="Inside_oligo2" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Inside_oligo2_m_oligo_inside_0" geometry={nodes.Inside_oligo2_m_oligo_inside_0.geometry} material={materials.m_oligo_inside} />
          </group>
          <group name="Oligodendrocyte2" position={[-20.526, -6.397, -7.073]} rotation={[-1.093, -0.108, -0.511]}>
            <mesh name="Oligodendrocyte2_Myelin3_0" geometry={nodes.Oligodendrocyte2_Myelin3_0.geometry} material={materials.Myelin3} />
          </group>
        </group>
        <mesh name="pCube5_phong2_0" geometry={nodes.pCube5_phong2_0.geometry} material={materials.phong2} scale={0.01} />
        <mesh name="Oligodendrocyte_Myelin3_0" geometry={nodes.Oligodendrocyte_Myelin3_0.geometry} material={materials.Myelin3} scale={0.01} />
        <mesh name="Inside_Oligo1_m_oligo_inside_0" geometry={nodes.Inside_Oligo1_m_oligo_inside_0.geometry} material={materials.m_oligo_inside} scale={0.01} />
        <mesh name="Main_Neuron3_phong1_0" geometry={nodes.Main_Neuron3_phong1_0.geometry} material={materials.phong1} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/terrain/neuronal_cell_environment_v1.glb')
