/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Teliko_comp.glb --transform 
Files: Teliko_comp.glb [2.22MB] > C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\terrain\Teliko_comp-transformed.glb [1.88MB] (16%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/terrain/Teliko_comp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <group position={[1.536, -1.972, -0.839]} scale={3.328}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Mesh_0_1.geometry} material={materials.DefaultMaterial} />
        </group>
        <mesh geometry={nodes.Grid.geometry} material={materials['Material.003']} position={[0, 24.536, 0]} scale={63.217} />
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[0, -26.7, 0]} scale={85.468} />
      </RigidBody>
      
      {/* INVISIBLE BOUNDARY WALLS */}
      {/* You can push these closer/further by changing the 'position' values! */}
      {/* args={[width/2, height/2, depth/2]} controls the size of the invisible box */}
      <RigidBody type="fixed">
        <CuboidCollider position={[60, 20, 0]} args={[1, 50, 60]} />  {/* Right boundary */}
        <CuboidCollider position={[-60, 20, 0]} args={[1, 50, 60]} /> {/* Left boundary */}
        <CuboidCollider position={[0, 20, 60]} args={[60, 50, 1]} />  {/* Back boundary */}
        <CuboidCollider position={[0, 20, -60]} args={[60, 50, 1]} /> {/* Front boundary */}
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/terrain/Teliko_comp.glb')
