/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\terrain\Teliko_model.glb --transform 
Files: C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\terrain\Teliko_model.glb [10.4MB] > C:\Users\Max\Desktop\B_Inquery\Frontend\Teliko_model-transformed.glb [770.35KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/terrain/Teliko_model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.atoms.geometry} material={materials.Material_0} position={[2.636, -0.259, -2.071]} />
      <mesh geometry={nodes.ribbons_mesh.geometry} material={materials.Material_1} position={[-0.422, 2.834, -0.508]} />
    </group>
  )
}

useGLTF.preload('/models/terrain/Teliko_model.glb')
