/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_paper.glb -T 
Files: the_paper.glb [0.36KB] > C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\Avatars\the_paper-transformed.glb [0.13KB] (64%)
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Float, Html } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function ThePaper(props) {
  const groupRef = useRef()
  const { scene } = useGLTF('/models/Avatars/The_paper.glb')
  const targetRotationY = useRef(0)
  const currentRotationY = useRef(0)
  const [showOverlay, setShowOverlay] = useState(false)
  const [inRange, setInRange] = useState(false)

  // Derive initial position from props or default
  const posArray = props.position || [0, 0, 0]
  const initialPosition = new THREE.Vector3(posArray[0], posArray[1], posArray[2])

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key.toLowerCase() === 'f' && inRange) {
        targetRotationY.current += Math.PI * 2
        setShowOverlay((prev) => !prev)
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [inRange])

  useFrame((state, delta) => {
    if (!groupRef.current) return
    currentRotationY.current = THREE.MathUtils.lerp(currentRotationY.current, targetRotationY.current, 10 * delta)
    groupRef.current.rotation.y = currentRotationY.current

    const dist = state.camera.position.distanceTo(initialPosition)
    if (dist < 15 && !inRange) setInRange(true)
    if (dist >= 15 && inRange) {
      setInRange(false)
      setShowOverlay(false)
    }
  })

  return (
    <group {...props} dispose={null}>
      {inRange && !showOverlay && (
        <Html position={[0, 4, 0]} center distanceFactor={15}>
          <div style={{ background: 'white', color: 'black', padding: '5px 12px', borderRadius: '15px', fontFamily: 'sans-serif', fontWeight: 'bold' }}>
            💭 Press F
          </div>
        </Html>
      )}
      {showOverlay && (
        <Html position={[0, 6, 0]} center distanceFactor={15} zIndexRange={[100, 0]}>
          <div style={{ background: '#fffae6', color: 'black', border: '3px solid #ffd700', padding: '15px', borderRadius: '8px', fontFamily: 'sans-serif', width: '220px', pointerEvents: 'none' }}>
            <h3 style={{ margin: '0 0 10px 0' }}>📄 My CV</h3>
            <p style={{ margin: 0, fontSize: '14px' }}>This is the magical floating CV.</p>
          </div>
        </Html>
      )}
      <Float speed={2} rotationIntensity={0.5} floatIntensity={1}>
        <group ref={groupRef}>
          <primitive object={scene} />
        </group>
      </Float>
    </group>
  )
}

useGLTF.preload('/models/Avatars/The_paper.glb')
