/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_pc.glb -T 
Files: the_pc.glb [1.71MB] > C:\Users\Max\Desktop\B_Inquery\Frontend\public\models\Avatars\the_pc-transformed.glb [181.96KB] (89%)
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Float, Html } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { GameState } from '../../store'

export function Model(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/models/Avatars/the_pc-transformed.glb')
  const targetRotationY = useRef(0)
  const currentRotationY = useRef(0)
  const [showOverlay, setShowOverlay] = useState(false)
  const [inRange, setInRange] = useState(false)

  // Derive initial position from props or default
  const posArray = props.position || [0, 0, 0]
  const initialPosition = new THREE.Vector3(posArray[0], posArray[1], posArray[2])

  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.key.toLowerCase() === 'f' || e.key.toLowerCase() === 'e') && inRange && !showOverlay) {
        targetRotationY.current += Math.PI * 2
        setTimeout(() => {
          setShowOverlay(true)
          GameState.isInteractionOpen = true
          if (GameState.controlsRef) GameState.controlsRef.enabled = false

          GameState.updateOverlay(
            <div style={{
              background: '#e6f7ff',
              color: 'black',
              border: '5px solid #00aaff',
              padding: '40px',
              borderRadius: '15px',
              fontFamily: 'monospace',
              width: '80vw',
              maxWidth: '600px',
              position: 'relative',
              boxShadow: '0 20px 40px rgba(0,0,0,0.5)'
            }}>
              <button 
                onClick={(e) => { 
                  e.stopPropagation(); 
                  setShowOverlay(false);
                  GameState.isInteractionOpen = false;
                  if (GameState.controlsRef) GameState.controlsRef.enabled = true;
                  GameState.updateOverlay(null);
                }}
                style={{
                  position: 'absolute',
                  top: '15px',
                  right: '15px',
                  background: 'transparent',
                  border: 'none',
                  color: 'red',
                  fontSize: '28px',
                  cursor: 'pointer',
                  fontWeight: 'bold',
                  padding: '5px',
                  transition: 'transform 0.2s',
                }}
                onMouseEnter={(e) => e.target.style.transform = 'scale(1.2)'}
                onMouseLeave={(e) => e.target.style.transform = 'scale(1)'}
              >
                ✕
              </button>
              <h2 style={{ margin: '0 0 20px 0', fontSize: '36px', fontFamily: 'sans-serif', color: '#111' }}>💻 PC Terminal</h2>
              <p style={{ fontSize: '18px', lineHeight: '1.6', margin: '0 0 30px 0', fontFamily: 'sans-serif' }}>
                Welcome to the interactive workstation. Use this terminal to analyze data or browse projects.
              </p>
              <div style={{ display: 'flex', gap: '20px' }}>
                <button style={{ 
                  border: 'none', cursor: 'pointer', padding: '12px 24px', background: '#00aaff', color: 'white', 
                  borderRadius: '8px', fontWeight: 'bold', fontSize: '16px', display: 'flex', alignItems: 'center', gap: '8px', fontFamily: 'sans-serif'
                }}>
                  Analyze Data
                </button>
                <button style={{ 
                  border: 'none', cursor: 'pointer', padding: '12px 24px', background: '#333', color: 'white', 
                  borderRadius: '8px', fontWeight: 'bold', fontSize: '16px', display: 'flex', alignItems: 'center', gap: '8px', fontFamily: 'sans-serif'
                }}>
                  View Projects
                </button>
              </div>
            </div>
          )
        }, 800)
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [inRange, showOverlay])

  useFrame((state, delta) => {
    if (!groupRef.current) return
    currentRotationY.current = THREE.MathUtils.lerp(currentRotationY.current, targetRotationY.current, 10 * delta)
    groupRef.current.rotation.y = currentRotationY.current

    const dist = state.camera.position.distanceTo(initialPosition)
    if (dist < 15 && !inRange) setInRange(true)
    if (dist >= 15 && inRange) {
      setInRange(false)
      setShowOverlay(false)
      GameState.updateOverlay(null)
    }
  })

  return (
    <group {...props} dispose={null}>
      {inRange && !showOverlay && (
        <Html position={[0, 1, 2]} center distanceFactor={15}>
          <div style={{ background: 'white', color: 'black', padding: '5px 12px', borderRadius: '15px', fontFamily: 'sans-serif', fontWeight: 'bold', pointerEvents: 'none' }}>
            💭 Press F
          </div>
        </Html>
      )}
      <group position={[0, 10, 0]}>
        <pointLight intensity={3000} color="#00aaff" />
        <mesh>
          <sphereGeometry args={[1, 16, 16]} />
          <meshBasicMaterial color="#00aaff" />
        </mesh>
      </group>
      <Float speed={2} rotationIntensity={0.5} floatIntensity={1}>
        <group ref={groupRef}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} position={[0, 0, 0]} rotation={[-1.682, 0.083, -0.638]} scale={[1.057, 1, 1.08]} />
        </group>
      </Float>
    </group>
  )
}

useGLTF.preload('/models/Avatars/the_pc-transformed.glb')
